server:
  port: 7001

eureka:
  instance:
    hostname: 127.0.0.1

  client:
    fetch-registry: false                  # 是否从注册中心获取消息
    register-with-eureka: false            # 是否将自己注册到eureka

    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka